server:
  port: 80
spring:
  profiles: local
  h2:
    console:
        path: /h2-test
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
---
server:
  port: 9090
spring:
  profiles: test